#!/bin/bash

take() {
  mkdir -p "${1}" \
    && cd "${1}"
}
jcar() {
  declare class="${1:-Main}"
  javac "${class%.*}.java" \
    && java "${class%.*}"
}
jbcar() {
  declare class="${1:-Main}"
  [[ ! -f ${class%.*}.java ]] \
    && echo "File ${class%.*}.java not found." \
    && return 1
  [[ ! -d "../bin" ]] \
    && mkdir "../bin"
  javac -d "../bin" "${class%.*}.java" \
    && java -classpath "../bin/" "${class%.*}"
}
sublime_text_bg() {
  sublime_text "$@" &
}

alias .='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ll='ls -lh'
alias la='ls -lah'
alias less='less -rSX'
alias cpr='cp -pr' # copy dir, preserve mode, ownership, timestamps
alias s='sublime_text_bg'
alias dstop='sudo docker stop $(sudo docker ps -a -q)'
alias fpull='flow --pull --conform'
alias fpush='flow --push --conform'
